create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id text primary key,
  name text not null,
  dealership_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.organizations (id, name, dealership_name)
values ('caskinette-ford', 'Caskinette Ford', 'Caskinette Ford')
on conflict (id) do update set
  name = excluded.name,
  dealership_name = excluded.dealership_name,
  updated_at = now();

create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  organization_id text not null references public.organizations(id) on delete cascade,
  setting_key text not null,
  setting_value jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, setting_key)
);

create table if not exists public.permit_batches (
  id text primary key,
  organization_id text not null default 'caskinette-ford' references public.organizations(id) on delete cascade,
  batch_date date not null,
  sheet_name text not null,
  source_file_name text not null default '',
  source_sheet_name text not null default '',
  imported_at timestamptz null,
  import_run_id text not null default '',
  check_number text not null default '',
  batch_number integer not null default 1,
  status text not null default 'Draft',
  notes text not null default '',
  printed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.permit_packets (
  id text primary key,
  organization_id text not null default 'caskinette-ford' references public.organizations(id) on delete cascade,
  batch_id text not null references public.permit_batches(id) on delete cascade,
  source_file_name text not null default '',
  source_sheet_name text not null default '',
  imported_at timestamptz null,
  import_run_id text not null default '',
  stock_number text not null default '',
  customer_name text not null default '',
  date_sold date null,
  registration_cost numeric(10,2) null,
  collected_amount numeric(10,2) null,
  owed_amount numeric(10,2) null,
  notes text not null default '',
  status text not null default 'Not Started',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.permit_batches enable row level security;
alter table public.permit_packets enable row level security;
alter table public.organizations enable row level security;
alter table public.app_settings enable row level security;

create policy "permit batches read" on public.permit_batches for select using (true);
create policy "permit batches write" on public.permit_batches for all using (true) with check (true);
create policy "permit packets read" on public.permit_packets for select using (true);
create policy "permit packets write" on public.permit_packets for all using (true) with check (true);
create policy "organizations read" on public.organizations for select using (true);
create policy "organizations write" on public.organizations for all using (true) with check (true);
create policy "settings read" on public.app_settings for select using (true);
create policy "settings write" on public.app_settings for all using (true) with check (true);

create index if not exists permit_batches_organization_batch_date_idx on public.permit_batches (organization_id, batch_date desc);
create index if not exists permit_batches_source_lookup_idx on public.permit_batches (organization_id, source_file_name, source_sheet_name, batch_date, check_number);
create index if not exists permit_batches_import_run_idx on public.permit_batches (import_run_id);
create index if not exists permit_packets_organization_batch_idx on public.permit_packets (organization_id, batch_id);
create index if not exists permit_packets_import_run_idx on public.permit_packets (import_run_id);
create unique index if not exists permit_batches_source_unique_idx on public.permit_batches (organization_id, source_file_name, source_sheet_name);

alter table public.permit_batches
  add column if not exists source_file_name text not null default '',
  add column if not exists source_sheet_name text not null default '',
  add column if not exists imported_at timestamptz null,
  add column if not exists import_run_id text not null default '';

alter table public.permit_packets
  add column if not exists source_file_name text not null default '',
  add column if not exists source_sheet_name text not null default '',
  add column if not exists imported_at timestamptz null,
  add column if not exists import_run_id text not null default '';

alter table public.permit_batches drop constraint if exists permit_batches_sheet_name_key;
